name             'chef-depot'
maintainer       'Jason Kulatunga'
maintainer_email 'jason@thesparktree.com'
license          'All rights reserved'
description      'Installs/Configures chef-depot'
long_description 'Installs/Configures chef-depot'
version          '0.1.0'
