name             'depot'
maintainer       'Jason Kulatunga'
maintainer_email 'jason@thesparktree.com'
license          'All rights reserved'
description      'Installs/Configures chef-depot'
long_description 'Installs/Configures chef-depot'
version          '0.1.0'

depends           'samba'
depends           'openssh'
depends           'python'
depends           'git'
depends           'apt'
depends           'database'
depends           'build-essential'
depends           'hostsfile'
depends           'docker_rancher'
depends           'logrotate'
supports 'ubuntu'